env:
  global:
  - secure: "an0P3r5z+91L0t4kCHsgQ7UZdVIgEXiDkdsDY4CuNHE1OR95WoihwzkB/fjLYV/5y26wUsBrN1TdAkQVnVwuIKifL5SUNK5L5DJZuOm0CPI1q2j/r9SrskMZoRIGCtuTRc5+MNpQ5rLm7HJwUHeUY43Qyk5VCZK/Lz4Co24cilwy0mNDEH9qqIx+pE3vcrbUqu7v2dCWub8TZ3K5cNQIdCg4186KUA1fU2HJSpcL4PA88N+XX9Oy3W6mnClhSqc2iD0WkZB8P+yCUOxGjsJgDNxAfzevRzc0Mmtmb+elDNEwKhpj9Xy4dKzKuw0msBhlOrIMQlA/jLPPvILmexLJHnaQH2zpA0Bp9e87LDSTOoKeAOkncCYjSzeqfhCr8sPEmV51v5zmZ/UumoNDIOCrr4BbG0h/vEn8We3ScyR3JyZFssbIRm26F21vHxkBoLQy66reep8YyS8U5LnDkTV/TLjGmCMDOdjlmOInua0qgFhuBWKtfSfyKTMCt3p3lcPdHZI3h4MpwzOQi+iHYtWMYb3CYVQy6/gWu+xpLEPpTWX0+kZGhbZclGDJGRjV0KGkTJ0qXMx62a0rSsOZfit+R4E18+c3aPv+boqT1OFCDT04l5B7IYlLt5U37AKpFkceU5RP2BXftU7y2KynZmsRAPvjfhQLbHGC7hevRGOwH0c="
language: php
php:
- 5.5
sudo: required
branches:
  only:
  - master
  - develop
before_script:
- make travisci-before-script
script:
- make travisci-script
after_success:
- make travisci-after-success
